name: deploying an EC2 instance
  on:
    push:
      branches: main 
  jobs:
    deploy:
      runs-on: macOS-latast
  env:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
